#!/usr/bin/env bash
# Ignore shellcheck SC2086

domain=$1
subdomain=$2

get_dns_info() {
    local sub=$1
    dig "$sub.$domain" | awk '
        $4 == "A" || $4 == "CNAME" {
            print "The subdomain " sub " is a " $4 " record and points to " $5
        }
    ' sub="$sub"
}

if [ -z "$subdomain" ]; then
    get_dns_info "www"
    get_dns_info "lb-01"
    get_dns_info "web-01"
    get_dns_info "web-02"
else
    get_dns_info "$subdomain"
fi

